---
apiVersion: v1
kind: Pod
metadata:
  name: flaskapi-pod1
  labels:
    app: flaskapi
    version: v1
spec:
  containers:
  - name: flaskapi
    image: ajaysinghdocker/flask-app
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 1m
        memory: 6000Mi
      requests:
        cpu: 1m
        memory: 2000Mi
    env:
    - name: APP_VERSION
      value: V1
    ports:
    - containerPort: 9999    

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: flaskapi
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service-node-port
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9999
  selector:
    app: flaskapi
  type: NodePort