---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment-2
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: myapp
          imagePullPolicy: Never
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: flaskapi
  type: LoadBalancer