---
apiVersion: v1
kind: Pod
metadata:
  name: flaskapi-pod1
  labels:
    app: flaskapi
    version: v1
spec:
  containers:
  - name: flaskapi
    image: myapp
    imagePullPolicy: Never
    env:
    - name: APP_VERSION
      value: V1
    ports:
    - containerPort: 9999    

---
apiVersion: v1
kind: Pod
metadata:
  name: flaskapi-pod2
  labels:
    app: flaskapi
    version: v2
spec:
  containers:
  - name: flaskapi-2
    image: myapp
    imagePullPolicy: Never
    env:
    - name: APP_VERSION
      value: V2
    ports:
    - containerPort: 9999        
---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: flaskapi
  type: LoadBalancer